### ISSUE TITLE
Is this project still active? 

### ISSUE THREAD

**Issue by ForeverWintr** [pybrain2/pybrain2#1]
I just did an install with pip, and when I try to `import pybrain2` I get an import error from `pybrain2/__init__.py`:

``` python
from pybrain.structure.__init__ import *
# builtins.ImportError: No module named 'pybrain'
```

It seems the import statement should be targeting pybrain2, not pybrain.

**Comment by cmorgan** [comment]
Hey, despite being called pybrain2 the namespace of the package is pybrain. This should either be made explicit in the README or indeed change the namespace to pybrain2.
